# Generated by Django 6.0.7 on 2026-07-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.PositiveIntegerField(unique=True)),
                ('league_id', models.PositiveIntegerField(blank=True, null=True)),
                ('league_name', models.CharField(blank=True, max_length=150)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round', models.CharField(blank=True, max_length=100)),
                ('kickoff_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('referee', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('LIVE', 'Live'), ('HT', 'Half Time'), ('FT', 'Finished'), ('PST', 'Postponed'), ('CANC', 'Cancelled'), ('AET', 'After Extra Time'), ('PEN', 'Penalties')], default='NS', max_length=4)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='players.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='players.team')),
            ],
            options={
                'ordering': ['kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('CARD', 'Card'), ('SUBST', 'Substitution'), ('VAR', 'VAR')], max_length=5)),
                ('detail', models.CharField(blank=True, max_length=150)),
                ('minute', models.PositiveSmallIntegerField()),
                ('extra_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assist_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_event_assists', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='players.team')),
            ],
            options={
                'ordering': ['minute', 'extra_minute'],
            },
        ),
    ]
