# Generated by Django 6.0.7 on 2026-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='football_data_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
