# Generated by Django 6.0.7 on 2026-07-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_backfill_refs_and_dedup_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='api_football_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='football_data_id',
        ),
    ]
