# Generated by Django 6.0.7 on 2026-07-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_api_football_id_and_more'),
        ('players', '0010_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)')], max_length=30),
        ),
        migrations.CreateModel(
            name='MatchTeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('corners', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_accurate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='players.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'team'), name='unique_match_team_statistics')],
            },
        ),
    ]
