# Generated by Django 5.2.16 on 2026-08-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_matchexternalref_source_matchteamstatistics'),
        ('players', '0010_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_formation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='home_formation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='clearances_effective',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='clearances_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='crosses_accurate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='crosses_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='interceptions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='long_balls_accurate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='long_balls_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='penalty_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='penalty_shots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='shots_blocked',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='tackles_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='tackles_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_type', models.CharField(max_length=60)),
                ('text', models.TextField(blank=True)),
                ('minute', models.PositiveSmallIntegerField()),
                ('extra_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('field_x', models.FloatField(blank=True, null=True)),
                ('field_y', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_plays', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_plays', to='players.team')),
            ],
            options={
                'ordering': ['minute', 'extra_minute', 'sequence'],
                'indexes': [models.Index(fields=['match', 'minute'], name='matches_mat_match_i_7a7afb_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'sequence'), name='unique_match_play_sequence')],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('formation_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subbed_in', models.BooleanField(default=False)),
                ('subbed_out', models.BooleanField(default=False)),
                ('goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('own_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_committed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_suffered', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('offsides', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_faced', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_conceded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_statistics', to='players.team')),
            ],
            options={
                'ordering': ['-starter', 'formation_place'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_player_match_statistics')],
            },
        ),
    ]
