# Generated by Django 5.2.16 on 2026-08-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_away_formation_match_home_formation_and_more'),
        ('players', '0010_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchplay',
            name='unique_match_play_sequence',
        ),
        migrations.AddField(
            model_name='matchplay',
            name='external_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='matchplay',
            constraint=models.UniqueConstraint(fields=('match', 'external_id'), name='unique_match_play_external_id'),
        ),
    ]
