# Generated by Django 5.2.16 on 2026-08-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_matchplay_unique_match_play_sequence_and_more'),
        ('players', '0011_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstatistics',
            name='key_passes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='minutes_played',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='xa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='xg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='xg_buildup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='xg_chain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)')], max_length=30),
        ),
        migrations.CreateModel(
            name='MatchShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40)),
                ('minute', models.PositiveSmallIntegerField()),
                ('xg', models.FloatField()),
                ('result', models.CharField(max_length=30)),
                ('situation', models.CharField(blank=True, max_length=30)),
                ('shot_type', models.CharField(blank=True, max_length=30)),
                ('last_action', models.CharField(blank=True, max_length=40)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_assists', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_shots', to='players.team')),
            ],
            options={
                'ordering': ['minute'],
                'indexes': [models.Index(fields=['match', 'minute'], name='matches_mat_match_i_3c7a3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('external_id',), name='unique_shot_external_id')],
            },
        ),
    ]
