# Generated by Django 5.2.16 on 2026-08-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_playermatchstatistics_key_passes_and_more'),
        ('players', '0012_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMomentum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30)),
                ('minute', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='matchshot',
            name='unique_shot_external_id',
        ),
        migrations.AddField(
            model_name='matchshot',
            name='goal_crossed_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchshot',
            name='goal_crossed_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchshot',
            name='is_blocked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchshot',
            name='is_from_inside_box',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchshot',
            name='is_on_target',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchshot',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], default='understat', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchshot',
            name='xgot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='big_chances',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='big_chances_missed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='dribbles_succeeded',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='duels_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='passes_opposition_half',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='passes_own_half',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='touches_opp_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='xg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='xg_non_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='xg_open_play',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='xg_set_play',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstatistics',
            name='xgot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='aerial_duels_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='blocks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='chances_created',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='clearances',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='defensive_actions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='dispossessed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='dribbled_past',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='dribbles_succeeded',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='duels_lost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='duels_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='goals_prevented',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='ground_duels_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='interceptions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='long_balls_accurate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='passes_accurate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='passes_into_final_third',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='recoveries',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='tackles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='touches',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='touches_opp_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='xgot_faced',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='matchshot',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_shot_source_external_id'),
        ),
        migrations.AddField(
            model_name='matchmomentum',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_points', to='matches.match'),
        ),
        migrations.AddConstraint(
            model_name='matchmomentum',
            constraint=models.UniqueConstraint(fields=('match', 'source', 'minute'), name='unique_match_source_minute_momentum'),
        ),
    ]
