# Generated by Django 5.2.16 on 2026-08-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_matchmomentum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmomentum',
            name='minute',
            field=models.FloatField(),
        ),
    ]
