# Generated by Django 5.2.16 on 2026-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_matchmomentum_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstatistics',
            name='formation_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='formation_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
