# Generated by Django 5.2.16 on 2026-08-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_playermatchstatistics_formation_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingests', to='matches.match')),
            ],
            options={
                'ordering': ['-ingested_at'],
                'constraints': [models.UniqueConstraint(fields=('match', 'source'), name='unique_match_source_ingest')],
            },
        ),
    ]
