# Generated by Django 5.2.16 on 2026-08-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_matchingest'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamstatistics',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playermatchstatistics',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
