# Generated by Django 5.2.16 on 2026-08-18 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_matchteamstatistics_field_sources_and_more'),
        ('players', '0012_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30)),
                ('kind', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source', 'kind'], name='matches_raw_source_7d56b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'kind', 'key'), name='unique_raw_payload')],
            },
        ),
        migrations.CreateModel(
            name='FieldConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('kept_source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30)),
                ('kept_value', models.CharField(max_length=60)),
                ('other_source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30)),
                ('other_value', models.CharField(max_length=60)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='players.team')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['match', 'field'], name='matches_fie_match_i_4ad745_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player', 'team', 'field', 'other_source'), name='unique_field_conflict')],
            },
        ),
    ]
