# Generated by Django 5.2.16 on 2026-08-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_rawpayload_fieldconflict'),
        ('players', '0012_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='1-11')),
                ('position', models.CharField(choices=[('GK', 'Kiper'), ('RB', 'Bek kanan'), ('CB', 'Bek tengah'), ('LB', 'Bek kiri'), ('DM', 'Gelandang bertahan'), ('CM', 'Gelandang tengah'), ('AM', 'Gelandang serang'), ('RW', 'Sayap kanan'), ('LW', 'Sayap kiri'), ('CF', 'Penyerang')], max_length=2)),
                ('confidence_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_key', models.BooleanField(default=False)),
                ('pitch_x', models.FloatField(blank=True, null=True)),
                ('pitch_y', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_slots', to='players.player')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='matches.predictionsnapshot')),
            ],
            options={
                'ordering': ['snapshot', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='HypothesisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('evidence_note', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(choices=[('BELUM', 'Belum terjawab'), ('KENA', 'Kena'), ('MELESET', 'Meleset')], default='BELUM', max_length=8)),
                ('outcome_note', models.CharField(blank=True, max_length=300)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='matches.predictionsnapshot')),
            ],
            options={
                'ordering': ['snapshot', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='predictionsnapshot',
            index=models.Index(fields=['match', '-created_at'], name='matches_pre_match_i_b3a921_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineupslot',
            constraint=models.UniqueConstraint(fields=('snapshot', 'slot'), name='unique_snapshot_slot'),
        ),
    ]
