# Generated by Django 5.2.16 on 2026-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_bersihkan_statistik_tim_nol_palsu'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstatistics',
            name='passes_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
