# Generated by Django 5.2.16 on 2026-08-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_bersihkan_shots_faced_nol_palsu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob')], max_length=30, unique=True)),
                ('last_ok_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['source'],
            },
        ),
    ]
