# Generated by Django 5.2.16 on 2026-08-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_sourceheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconflict',
            name='kept_source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fieldconflict',
            name='other_source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchingest',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchmomentum',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchshot',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rawpayload',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sourceheartbeat',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='SavedMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=300)),
                ('figure', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(blank=True, choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30)),
                ('origin_card', models.CharField(blank=True, max_length=10)),
                ('origin', models.CharField(choices=[('analis', 'Ditandai analis'), ('sistem', 'Dihitung dari data akhir')], default='analis', max_length=6)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_moments', to='matches.match')),
            ],
            options={
                'ordering': ['minute', 'id'],
                'indexes': [models.Index(fields=['match', 'origin'], name='matches_sav_match_i_b53129_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('origin', 'sistem')), fields=('match', 'origin_card', 'text'), name='unique_system_moment_per_match')],
            },
        ),
    ]
