# Generated by Django 5.2.16 on 2026-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_alter_fieldconflict_kept_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypothesisitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
