# Generated by Django 6.0.7 on 2026-07-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre-Back'), ('RB', 'Right-Back'), ('LB', 'Left-Back'), ('CDM', 'Defensive Midfield'), ('CM', 'Central Midfield'), ('CAM', 'Attacking Midfield'), ('WNG', 'Winger'), ('CF', 'Centre-Forward')], max_length=3)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('on_loan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_manchester_united', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OUT', 'Out'), ('DOUBTFUL', 'Doubtful'), ('RETURNED', 'Returned')], default='OUT', max_length=10)),
                ('start_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='players.player')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.team'),
        ),
    ]
