# Generated by Django 6.0.7 on 2026-07-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team_football_data_id_alter_team_api_football_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org')], max_length=30)),
                ('external_id', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='players.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_team_source_external_id')],
            },
        ),
    ]
