# Generated by Django 6.0.7 on 2026-07-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_teamexternalref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_football_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='football_data_id',
        ),
    ]
