# Generated by Django 6.0.7 on 2026-07-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remerge_teams_prefix_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='api_football_id',
        ),
        migrations.AlterField(
            model_name='teamexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlayerExternalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly')], max_length=30)),
                ('external_id', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_refs', to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_player_source_external_id')],
            },
        ),
    ]
