# Generated by Django 6.0.7 on 2026-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('premier_league', 'Premier League (PulseLive)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teamexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('premier_league', 'Premier League (PulseLive)')], max_length=30),
        ),
    ]
