# Generated by Django 5.2.16 on 2026-08-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_playerexternalref_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teamexternalref',
            name='source',
            field=models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30)),
                ('status', models.CharField(choices=[('FIT', 'Bugar'), ('DOUBT', 'Diragukan'), ('OUT', 'Absen'), ('SUSP', 'Skorsing'), ('LOAN', 'Dipinjamkan'), ('UNK', 'Tidak dicakup sumber')], max_length=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('chance_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'player availability',
                'ordering': ['player__name', 'source'],
                'constraints': [models.UniqueConstraint(fields=('player', 'source'), name='unique_player_source_availability')],
            },
        ),
    ]
