# Generated by Django 5.2.16 on 2026-08-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_playeravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api_football', 'API-Football'), ('football_data', 'football-data.org'), ('highlightly', 'Highlightly'), ('thesportsdb', 'TheSportsDB'), ('espn', 'ESPN'), ('espn_commentary', 'ESPN (parsed dari commentary teks)'), ('premier_league', 'Premier League (PulseLive)'), ('understat', 'Understat (xG)'), ('fotmob', 'FotMob'), ('fpl', 'Fantasy Premier League'), ('news', 'Umpan berita')], max_length=30)),
                ('status', models.CharField(choices=[('FIT', 'Bugar'), ('DOUBT', 'Diragukan'), ('OUT', 'Absen'), ('SUSP', 'Skorsing'), ('LOAN', 'Dipinjamkan'), ('UNK', 'Tidak dicakup sumber')], max_length=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_decision', to='players.player')),
            ],
            options={
                'ordering': ['player__name'],
            },
        ),
    ]
