# Generated by Django 5.2.16 on 2026-08-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=80)),
                ('publisher_group', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('A', 'A — catatan resmi'), ('B', 'B — media berbadan hukum'), ('C', 'C — blog / agregat')], max_length=1)),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=600, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('quoted_source', models.CharField(blank=True, max_length=80)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsit_publish_708086_idx'), models.Index(fields=['publisher_group'], name='news_newsit_publish_04f0e6_idx')],
            },
        ),
    ]
